/*
 * CreativeConnect — static site export for GitHub Pages.
 * Produces a /docs folder (which GitHub Pages can serve) containing the public
 * marketing site only. There is NO backend on Pages, so:
 *   - home/trust/footer content is baked in from the current DB (server-rendered once)
 *   - config.js is generated with staticMode:true (booking uses WhatsApp fallback)
 *   - the admin dashboard, database and lead storage are NOT included
 *
 * Run:  npm run build:static
 */
"use strict";

const fs = require("fs");
const path = require("path");
const { renderHome } = require("../server/render");
const { getPublicConfig } = require("../server/db");

const ROOT = path.join(__dirname, "..");
const OUT = path.join(ROOT, "docs");
// Public GitHub Pages URL for this repo (used for SEO absolute URLs).
const BASE = process.env.PAGES_BASE || "https://iyaash-ahmed.github.io/creativeconnect";

function log(msg) { console.log("[build:static] " + msg); }

// 1. Clean output
fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

// 2. Home page — server-render once so {{...}} placeholders + JSON-LD are baked in
fs.writeFileSync(path.join(OUT, "index.html"), renderHome(BASE));
log("index.html rendered");

// 3. Copy assets, then the other static pages
fs.cpSync(path.join(ROOT, "assets"), path.join(OUT, "assets"), { recursive: true });
["booking.html", "thanks.html", "privacy.html", "404.html", "IMAGES.md"].forEach((f) => {
  const src = path.join(ROOT, f);
  if (fs.existsSync(src)) fs.copyFileSync(src, path.join(OUT, f));
});
log("assets + pages copied");

// 3b. Admin dashboard — REAL, Supabase-powered (no Node backend on Pages).
//     Deploy admin/supabase.html as /admin/index.html. It loads config.js
//     (supabase url + anon key) and assets/js/supabase-admin.js (both already
//     copied above / generated below). The Node admin (admin/admin.js) is NOT
//     shipped to the static build.
fs.mkdirSync(path.join(OUT, "admin"), { recursive: true });
fs.copyFileSync(path.join(ROOT, "admin", "supabase.html"), path.join(OUT, "admin", "index.html"));
log("admin (Supabase-powered) deployed");

// 4. Overwrite config.js with a static build (staticMode:true bakes in content)
const cfg = Object.assign({}, getPublicConfig(), { staticMode: true });
const configJs =
  "/* Static build for GitHub Pages — generated by scripts/build-static.js.\n" +
  "   Edit content in the admin (Node app) and re-run `npm run build:static`. */\n" +
  "window.CC_CONFIG = " + JSON.stringify(cfg).replace(/</g, "\\u003c") + ";\n";
fs.mkdirSync(path.join(OUT, "assets", "js"), { recursive: true });
fs.writeFileSync(path.join(OUT, "assets", "js", "config.js"), configJs);
log("config.js generated (staticMode)");

// 5. SEO helpers + Pages niceties
fs.writeFileSync(
  path.join(OUT, "robots.txt"),
  "User-agent: *\nAllow: /\nSitemap: " + BASE + "/sitemap.xml\n"
);
const today = new Date().toISOString().slice(0, 10);
const pages = [["/", "1.0"], ["/booking.html", "0.9"], ["/privacy.html", "0.3"]];
fs.writeFileSync(
  path.join(OUT, "sitemap.xml"),
  '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' +
    pages.map((p) => "  <url><loc>" + BASE + p[0] + "</loc><lastmod>" + today + "</lastmod><priority>" + p[1] + "</priority></url>").join("\n") +
    "\n</urlset>\n"
);
// .nojekyll so GitHub Pages serves files/folders as-is (no Jekyll processing)
fs.writeFileSync(path.join(OUT, ".nojekyll"), "");
log("robots.txt, sitemap.xml, .nojekyll written");

log("done → " + OUT);
